### ISSUE TITLE
Reactome: R-HSA-5683569 has multiple issues

### ISSUE THREAD

**Issue by nataled** [geneontology/pathways2GO#146]
R-HSA-5683569 (CysO263-ATG3) has a modification at position 263 indicated by MOD:01777. The description of the reaction states "The activated LC3 protein is transferred to Cys-263 of ATG3 through a thioester bond." A number of discrepancies thus arise:

1) Position 263 in ATG3 is a proline.
2) MOD:01777 is specifically for a link between a C-terminal glycine residue to a free cysteine. Each of the 'LC3' proteins (all members of the set, plus the candidate member) has a C-terminal glycine (verified), so that part is okay, but--assuming the correct position is found--the connection would not be to a free cysteine.
3) As the described connection is between two proteins (or, as in this case, between a protein and a member of a set), there should be an indication of that, much like what is done for SUMO etc.

**Comment by nataled** [comment]
It is likely similar issues exist with R-HSA-5683584.

**Comment by deustp01** [comment]
The incorrect residue is straightforward to fix but the rest is complicated (there's a set of proteins buried at the place in the data structure where a modifying group belongs) and will need re-curation to untangle. We do have a class that allows us to annotate the covalent joining of two different gene products to form a single physical entity, mostly applied so far to annotate disulfide bonds, but sometimes to annotate other kinds of covalent linkages between side chains of different proteins, e.g., [R-HSA-5653752](https://reactome.org/content/detail/R-HSA-443648).

This may be an issue for the future. So far. for ubiquitination and SUMOylation it's probably OK to ignore the fact that ubiquitin and SUMO are themselves gene products and just treat them as chemical adducts on the target protein, without distorting biology for our users. For these other cross-linking cases, that may not be true. But before we reach that issue, I need to figure out exactly what is getting attached to what in the instances you have flagged.

**Comment by deustp01** [comment]
All fixed

- [x] R-HSA-5683569 (CysO263-ATG3) annotation corrected to point to Cys-264
- [x] For R-HSA-5683569 (CysO263-ATG3) and R-HSA-5683584 interchain crosslink modification corrected to psiMOD:00211 to show connection of a glycyl residue to a cystinyl residue rather than  to  free cysteine.
- [x] previous annotations of ATG3 and ATG7 with LC3 family proteins as ATG:LC3 complexes have been corrected to represent ATG proteins covalently modified via interchain crosslinks to LC3 proteins.
- [x] reactions R-HSA-5682011, -5682896, -5681981, -5683593, and -5678490 corrected to use these corrected entities and entity sets as inputs, outputs, and catalysts.

To do, but this is really a separate issue beyond the scope of this ticket: review this material for conformity to current Reactome standard practices for annotating ubiquitination-like processes.

So closing this ticket.
