### ISSUE TITLE
Immediate Reload Reactome Pathways 

### ISSUE THREAD

**Issue by ukemi** [geneontology/pathways2GO#160]
We need to Reload the Reactome Models because they are stale.

**Comment by ukemi** [comment]
- [ ] - One-time update of models ASAP because they are stale. 
- [ ] - Replace transports_or_maintains_localization_of relations with has_primary_input
- [ ] - Remove models that are a single node. Eg gomodel:R-HSA-71291
- [ ] - Update obsolete entities with replacement terms. Provide a report to Reactome of changes.

**Comment by dustine32** [comment]
Thanks for making this ticket @ukemi! I plan on starting the one-time update of latest Reactome release into noctua-dev sometime this week.

**Comment by deustp01** [comment]
Feature creep: we are going to need regular updates to keep the Reactome-derived GO-CAM set up to date with revisions in Reactome content and additions of new content so a really important side-product of this "one time" update will be ideas about how to do this updating efficiently and as nearly automatically as possible. @ukemi anything to add here?

**Comment by ukemi** [comment]
#162

**Comment by dustine32** [comment]
@ukemi @deustp01 I've regenerated models from the latest Reactome release 80. One unexpected thing is that running the pathways2go code as-is results in far fewer models than expected, 1885 out of the 2580 human pathways in Reactome. It turns out this is due to a "flag" `ignore_diseases` that "skips any pathway that has the word 'disease' in its name or any of its parent pathway's name" and is hard-coded set to `true`. Changing `ignore_diseases` to `false` produces the expected 2580 models.

So, should we be loading these "disease" pathways into Noctua or skipping them?

Noting that Noctua currently shows 1817 models with title containing "imported from: Reactome". So, leaning towards us skipping disease pathways.

**Comment by deustp01** [comment]
Thanks!

Editorial / scope decision so far is, GO only considers normal biology so Reactome disease pathways are out of scope for GO-CAM conversion, at least for now. We checked the earlier build to be sure that Ben’s skip flag was working right, and the addition of ~70 new pathways since then seems about right, so the result is plausible. (There's also a flag to exclude anything tagged as a "drug", which may knock out a few more.)

**Comment by ukemi** [comment]
Is it time for us to start reviewing these? Shall we discuss a strategy on today's call?

**Comment by deustp01** [comment]
Yes to both. One good place to start is to get a list by R-HSA-id of all pathways in the new build that were not in the previous one. Also from the Reactome side, a list of all pathways that have been revised since the previous build, to focus on the changed material. And a list of any that were in the previous one and dripped out (probably none - this is a sanity check). Beyond that, what to look for in the re-built pathways is an item for discussion today.

**Comment by ukemi** [comment]
@deustp01 and @ukemi should check the new cobalamin metabolism imports to sanity check the new biology.

**Comment by ukemi** [comment]
Actually, cobalamin might not go live until the new release. @deustp01 do you know some pathways that we worked on that were part of releases between the last load and the biopax that @dustine32 is picking up currently?

**Comment by ukemi** [comment]
@deustp01 and @dustine32 to aggressive to go for the June 9 maintenance window? If so, then June 23?

**Comment by deustp01** [comment]
[Cobalamin](https://reactome.org/PathwayBrowser/#/R-HSA-9759218) is already live, as are all the scattered edits to [normal purine catabolism](https://reactome.org/content/detail/R-HSA-74259)

**Comment by dustine32** [comment]
Preliminary report of just R-HSA pathway models added or removed between the release loaded into Noctua prod and the newest Reactome release 80:

**Added (70)**
R-HSA-201556
R-HSA-5620971
R-HSA-8980692
R-HSA-9012999
R-HSA-9013026
R-HSA-9013106
R-HSA-9013148
R-HSA-9013149
R-HSA-9013404
R-HSA-9013405
R-HSA-9013406
R-HSA-9013407
R-HSA-9013408
R-HSA-9013409
R-HSA-9013418
R-HSA-9013419
R-HSA-9013420
R-HSA-9013422
R-HSA-9013423
R-HSA-9013424
R-HSA-9013425
R-HSA-9035034
R-HSA-9634597
R-HSA-9659379
R-HSA-9662360
R-HSA-9662361
R-HSA-9667769
R-HSA-9674555
R-HSA-9686347
R-HSA-9690406
R-HSA-9696264
R-HSA-9696270
R-HSA-9696273
R-HSA-9701898
R-HSA-9705462
R-HSA-9706019
R-HSA-9706369
R-HSA-9706374
R-HSA-9706574
R-HSA-9707564
R-HSA-9707587
R-HSA-9707616
R-HSA-9708296
R-HSA-9708530
R-HSA-9709957
R-HSA-9711097
R-HSA-9711123
R-HSA-9715370
R-HSA-9716542
R-HSA-9717189
R-HSA-9717207
R-HSA-9729555
R-HSA-9729902
R-HSA-9730628
R-HSA-9730737
R-HSA-9734091
R-HSA-9748784
R-HSA-9748787
R-HSA-9749641
R-HSA-9750126
R-HSA-9752946
R-HSA-9753281
R-HSA-9754119
R-HSA-9754706
R-HSA-9755511
R-HSA-9758881
R-HSA-9758890
R-HSA-9759194
R-HSA-9759218
R-HSA-9762114

**Removed (2)**
R-HSA-194840
R-HSA-68827

Will follow up with the ShEx results for the whole load (and will confirm they all pass OWL logical consistency checks).

**Comment by ukemi** [comment]
@deustp01 and @dustine32 , does the division of labor and the scheduling in the first comment of this ticket seem doable? Otherwise we should reschedule the release of the new load for the 23rd.

**Comment by ukemi** [comment]
Glycolysis sanity check
The import still looks consistent and true to the data from Reactome. The model does not include the new has_small_molecule_regulator relation and does display many reactions that impinge upon canonical glycolysis but are not a part of it. This opens up some nice discussions about how to display interacting pathways, but for the purpose of this import checking, this model passes the validity test.

**Comment by ukemi** [comment]
Ah, that explains a lot! Sorry about the confusion. I've pushed out the release date to the 23rd so we are not in such a crunch. Thanks @dustine32!

**Comment by dustine32** [comment]
@ukemi Thank you! Yes, the 23rd should definitely be enough time for testing and fixing any discovered major issues.

**Comment by deustp01** [comment]
> Preliminary report of just R-HSA pathway models added or removed between the release loaded into Noctua prod and the newest Reactome release 80:

Checked all 70 new pathways in our internal database. All were publicly released between 2020-09-15 and 2022-03-23, which I think is since the closing date for the previous set of models. The two pathways flagged by Dustin as removed were indeed deleted and replaced by new pathways: note that in one case Dustin identified the replacements and in the other case I can't tell whether a GO-CAM has been generated from the replacement pathway.

"Say no to drugs" - it looks like seven of the new pathways involve drugs. Can we manually exclude these models now and then try to improve our drug testing program to exclude them automatically in the future?

**Comment by dustine32** [comment]
@deustp01 Sure, I can manually exclude those models marked "DRUG" before they get into Noctua production.

As far as automating this, there's _another_ flag hard-coded to `true` specifically to remove drug reactions:
https://github.com/geneontology/pathways2GO/blob/9ac81db73cfff952739b6701203132a05837fb80/exchange/src/main/java/org/geneontology/gocam/exchange/BioPaxtoGO.java#L137
Without debugging to confirm, it looks like this would only remove the reactions and not the entire pathway. Should this switch to completely skip these pathways?

Possibly related, we found a [bug](https://github.com/geneontology/pathways2GO/issues/136) in the reacto build a while back where all IUPHAR mappings got dropped. This could be affecting detection of drug entities in the translation. Luckily, we have a [unit test](https://github.com/geneontology/pathways2GO/blob/9ac81db73cfff952739b6701203132a05837fb80/exchange/src/test/java/org/geneontology/gocam/exchange/BioPaxtoGOTest.java#L361) we can run to see if this is still happening.

**Comment by dustine32** [comment]
@ukemi @deustp01 Attached here is the ShEx validation report for all 1885 Reactome models in this load. Bad news: 1462 failed ShEx (but 423 passed). All models were OWL consistent. We can dig in to some of the failing models to search for patterns.
[shex_report_20220607.txt](https://github.com/geneontology/pathways2GO/files/8857708/shex_report_20220607.txt)

Hopefully, the new models will be available in noctua-dev for testing by tomorrow (2022-06-08) as the dev server is cycling right now.

**Comment by ukemi** [comment]
Looking at the current models on the production server, it looks like these fail the Shex too. Is this good news or not. Having a quick look at chondroitin sulfate biosynthesis, it looks like we are violating something about location of functions. We have the function (GO:0015018) occurring in the golgi membrane (GO:0000139). This seems fine from a rule perspective although there is still the weirdness about membrane locations and where they catalyze their reactions (a discussion for another day). I just looked at some of my models that I created based on the Reactome imports and although I see some Shex violations, most that are similar to this seem fine. Is there some reason that in the model we are not inferring that the golgi membrane is an anatomical structure? In the meantime, since this seems to be a problem with the current models, do we go ahead with this and say we are no worse off?
Here is an example of the ShEX report from R-HSA-1793217 on production:
[
   {
      "shape": "obo:go/shapes/MolecularFunction",
      "constraints": [
         {
            "object": "gomodel:reaction_R-HSA-1793217_location_lociGO_0043202",
            "property": "BFO:0000066",
            "node_types": [
               "GO:0004565"
            ],
            "object_types": [
               "GO:0043202"
            ],
            "nobjects": 0,
            "matched_range_shapes": [

            ],
            "intended-range-shapes": [
               "obo:go/shapes/AnatomicalEntity"
            ]
         }
      ]
   }
]

**Comment by deustp01** [comment]
> @deustp01 Sure, I can manually exclude those models marked "DRUG" before they get into Noctua production.
> 
> As far as automating this, there's _another_ flag hard-coded to `true` specifically to remove drug reactions:
> 
> [](https://github.com/geneontology/pathways2GO/blob/9ac81db73cfff952739b6701203132a05837fb80/exchange/src/main/java/org/geneontology/gocam/exchange/BioPaxtoGO.java#L137)

Thinking more, I realize there is a scope issue to discuss.

Ben's existing flag removes individual reactions in which a drug interacts with a normal physical entity and changes the entity's behavior, typically inactivating it. As Reactome includes these reactions showing effects of drugs as part_of the pathways that the normal entities normally participate in, this flag has the effect of stripping the "drug" reactions out of a normal pathway, leaving only the normal parts to go into the GO-CAM model. We continue to want that.

In the "ADME" cases, we are actually annotating all the other steps in a drug's interaction with the body: administration (uptake), distribution, metabolism, and elimination. So the scope / strategy question is whether ADME pathways are legitimate examples of xenobiotic metabolism and thus within scope for GO. @ukemi @vanaukenk ?

**Comment by deustp01** [comment]
> Preliminary report of just R-HSA pathway models added or removed between the release loaded into Noctua prod and the newest Reactome release 80:

More checking: I looked in our internal database for all pathways whose _doRelease toggle is "true", whose species is Homo sapiens, whose disease attribute is NULL, and whose release date is anywhere in the range 2020-09-15 to 2022-03-23, and found a total of 68 (versus 70 in Dustin's list. One of the pathways on the list but not found in my search is R-HSA-9686347 RIPK1 new 2020-09-15 (I noticed it because I was expecting to retrieve at least one pathway with a 2020-09-15 release date from my earlier survey, but retrieved none. This pathway has a non-NULL disease attribute, so we need to figure out why Dustin used it, but that is a separate issue.). That makes 69.

The 70th pathway retrieved by Dustin but not on my list of all pathways released on or after 2020-09-15 is
 - R-HSA-9012999 (RHO GTPase cycle) new - 2007 pathway revised 2020-07 and 2021-03
In our internal data base this pathway has a release date of 2007-05-15. This early release date is inconsistent with the pathway's identifier - R-HSA-9012999 - because these are assigned as ascending consecutive integers and in 2007 we were still in the hundred-thousands, not the millions. I expect that what happened here is that the curator, to try to show that the new collection of GTPase pathways descends from / expands on the original limited 2007 pathway, used its relwadse date on the new pathway. That is legal - these are entered manually, and we don[t have any rule prohibiting use of an old date to make a new pathway look like an old one. We may want to change this at Reactome.

Meanwhile, the tally is now consistent: the number of new-since-2020-09-15 in Dustin's build and in our internal database.

**Comment by deustp01** [comment]
> Looking at the current models on the production server, it looks like these fail the Shex too.

I took Dustin's shex report shex_report_20220607.txt, put it into an Excel workbook and in the second sheet of the workbook, sorted the sheet by model_url and then by shex_valid. The first parameter sorts the models ASCIbetically by R-HSA-number (so R-HSA-1 before -10 before -2 before -20 etc) which will put models from old pathways mostly at the top and new ones at the bottom, as these almost all have numbers greater than 9000000. Here's the file, in case it's useful:
[shex_report_20220607.xlsx](https://github.com/geneontology/pathways2GO/files/8863073/shex_report_20220607.xlsx)

**Comment by ukemi** [comment]
LOL,  It must be useful because I did the same sort to my local copy. I'm still not seeing the new models on dev and I looked at the ShEX violations in the production models with @vanaukenk this morning. We are a bit stumped, but conclude they are on the GOC side and are not issues with the biology in or coming from Reactome.

**Comment by dustine32** [comment]
Yep, sorry @ukemi @deustp01 for the delay! The new Reactome load is now in noctua-dev (at least as of 1pm Pacific today).

**Comment by ukemi** [comment]
No worries @kltm. Since we pushed the switch to production out to the next maintenance cycle, the pressure is off. @dustine32 do you want to look at the ShEx violations together at some point? I'll start QCing our favorite models this afternoon and indicate it in the task list above.

**Comment by ukemi** [comment]
https://github.com/geneontology/pathways2GO/issues/160#issuecomment-1149846392

My 2 cents: 

1. I think we should include these pathways where the drug is acted upon by the body, but maybe bring this to an ontology call because I'm not sure I am up to date with current thinking.
2. Perhaps open a ticket that captures the drugs interacting and modifying activities with the new has_small_molecule_regulator framework since we have chosen to go that route?

**Comment by ukemi** [comment]
@dustine32 
Investigate why R-HSA-9686347 RIPK1 new 2020-09-15 is_DISEASE! *** was allowed through in the load.

**Comment by ukemi** [comment]
glycolytic process (gomodel:R-HSA-70171)

- Has small molecule regulator has not been implemented
- Core process from glucokinase through pyruvate looks good.
- There are now a lot of molecular functions in the model that are not part of the core process. This is a good thing frm a data perspective because it is true, but it does muddy the model a bit for vizualization.
- We should make R-HSA-5696021 a preceding event of R-HSA-70471  (edits for next Reactome load)
- Should we make R-HSA-8955760a preceding event for R-HSA-71654? (edits for next Reactome load)
- All other paths and relationships are consistent with the source Reactome data.

**Comment by dustine32** [comment]
@deustp01 @ukemi I looked into the disease pathway getting through and I think I've figured out what's going on. Current "is disease"-checking logic is to traverse up the `pathwayComponentOf` chain for a given pathway until it finds a parent/ancestor pathway with display name == "Disease". A working example for [R-HSA-9664323](https://reactome.org/content/detail/R-HSA-9664323) as seen in Reactome shows how this hierarchy works:
![image](https://user-images.githubusercontent.com/2678599/172918885-f5baf27c-0059-4f53-9d56-340affeec765.png)
The check will find the "parent" pathway labeled "Disease" and use that to determine R-HSA-9664323 is a disease pathway and should be skipped.

Now, our current failing example pathway [R-HSA-9686347](https://reactome.org/content/detail/R-HSA-9686347) in Reactome:
![image](https://user-images.githubusercontent.com/2678599/172918829-2f463c62-a2f8-4de4-bda3-840a5a528718.png)
As you can see, the hierarchy does not lead to a parent pathway labeled "Disease." _But_ In both pathways here you can see that red `+` symbol indicating that the Reactome site knows these are disease pathways. We need to figure out what data/property of the pathway the Reactome site code uses for displaying this symbol and then port that logic over to the pathways2GO code.

**Comment by deustp01** [comment]
The model R-HSA-9755511 (from Reactome pathway KEAP, new 2022-03-23) includes a single disease reaction. My editorial opinion (but definitely subject to review! @dustine32 @ukemi @vanaukenk) is that allowing this otherwise OK-looking model to get uploaded with the one out-of-scope reaction in it is OK for now.

The long-term fix, I suspect, is to add a test like the one already in place for drug reactions in otherwise normal pathways. (That test detects reactions that have physical entities with a non-NULL "drug" attribute as inputs and does not use them to build the GO-CAM for the Reactome pathway, so the GO-CAM simply has a gap in those places.) Here, could we test for reactions whose "disease" attribute is not NULL and omit them when building the GO-CAM, to again yield a GO-CAM with a gap.

My best guess is that "disease" reactions in otherwise normal pathways, like "drug" reactions, are rare and they mostly show up as branches that diverge from the main flow of the pathway, so the resulting gaps will noty get in the way of visualizing / navigating / mining the GO-CAM representation of the pathway.

This PowerPoint file has screenshots of relevant bits of the Reactome pathway and of the GO-CAM built from it:
[disease_reaction_in_normal_pathway.pptx](https://github.com/geneontology/pathways2GO/files/8882165/disease_reaction_in_normal_pathway.pptx)

**Comment by ukemi** [comment]
For R-HSA-9755511, I agree with everything above. At least in this case, removing the disease reaction would just knock out the one regulatory step where the product inhibits R-HSA-8932327. Is this the only one like this?

**Comment by ukemi** [comment]
In this pathway, we have inferred the initial binding reaction as an event that is part of the pathway. Then we also have the subsequent event that involves the bound complex as a negatively regulates step.

**Comment by deustp01** [comment]
> In this pathway, we have inferred the initial binding reaction as an event that is part of the pathway. Then we also have the subsequent event that involves the bound complex as a negatively regulates step.

This disease reaction sequence is exactly analogous to the drug reaction sequences that Ben's process reliably finds and suppresses: normal protein + drug -> normal protein:drug complex provides_input_for normal protein:drug complex negatively_regulates event(s) enabled by the normal protein.

So I hope that Ben's drug test can be adapted to find and suppress these stray disease reactions.

Meanwhile we are taking a look at Reactome to try to tally the exact number of disease reactions now annotated as part_of normal pathways.

**Comment by ukemi** [comment]
For the drugs, IIRC we filter on the entity type to be a drug. We will need something else here.

**Comment by deustp01** [comment]
> We will need something else here.

An attribute of the reactionlikeEvent class is "disease", which must be empty / null for normal reactions and must contain one or more Disease Ontology terms for disease reactions.

**Comment by ukemi** [comment]
@dustine32 how difficult is it for you to modify the code to add the above annotations? Should I open a separate issue?

**Comment by deustp01** [comment]
@dustine32 new bug? In gomodel:R-HSA-5620971, this activity unit corresponds to a reaction with a drug molecule (antabuse) as an input. Isn't the model-building process supposed to look for reactions with entities that are labeled "drug" and omit those reactions from GO-CAM models?
<img width="216" alt="Screen Shot 2022-06-13 at 6 13 12 PM" src="https://user-images.githubusercontent.com/12737623/173454989-a19e88fa-6b7d-4b6f-828b-e93e9531ab6d.png">

**Comment by dustine32** [comment]
@ukemi If you want to open a ticket for this that would definitely help me! I just need to standardize adding these properties (date, contributor, providedBy) to every individual, similar to https://github.com/geneontology/gocamgen/issues/86 and https://github.com/geneontology/gocamgen/issues/89. Shouldn't be too difficult.

**Comment by dustine32** [comment]
@deustp01 Yes, I'm pretty certain that is a bug. In fact I don't think the code is currently able to recognize any entities as "drug" because it specifically looks for presence of an IUPHAR mapping to an entity class (e.g. R-ALL-9693326) but there are no longer any IUPHAR mappings present in either the release 80 BioPAX nor the current [reacto.owl](http://purl.obolibrary.org/obo/go/extensions/reacto.owl). I believe this is the same issue causing https://github.com/geneontology/pathways2GO/issues/136 so we can correspond further in that ticket.

**Comment by dustine32** [comment]
@deustp01 @ukemi New models with #136 and #177 fixed are now in PR https://github.com/geneontology/noctua-models/pull/238 but not yet loaded to noctua-dev. I'm running ShEx validation right now and should have the report for you Tues morning-ish.

**Comment by dustine32** [comment]
@deustp01 @ukemi Actually, validation just finished and the report is attached:
[shex_report_20220620.txt](https://github.com/geneontology/pathways2GO/files/8944808/shex_report_20220620.txt)

Great news - all models passed ShEx except for these seven:
R-HSA-9708296
R-HSA-110381
R-HSA-1474151
R-HSA-4615885
R-HSA-2514859
R-HSA-73930
R-HSA-9706369

**Comment by deustp01** [comment]
I agree - I think we can go ahead with the re-load!

**Comment by deustp01** [comment]
Meanwhile, I will try to fix the obsolete BP term and multi-MF annotation in preparation for the version 82 re-build.

**Comment by dustine32** [comment]
@ukemi You may have been viewing an older version of R-HSA-9708296 in noctua-dev. The new models were loaded to noctua-dev ~10AM Pacific today (6/21). Can you check again? I now see the date, contrib, providedBy metadata properties added to that individual. There is still a ShEx error on one of the reactions though I think that's caused by something with the input/output REACTO entities. Not yet sure why those entities are failing.

**Comment by dustine32** [comment]
@deustp01 I can look into why there are multiple enablers for that reaction R-HSA-9706369. It seems like the conversion code should be made to catch this?

**Comment by ukemi** [comment]
So, I take back my analysis from this morning. I was probably looking at outdated models. Shall we examine these seven ShEx failures and open tickets in each one for the next Reactome load? I think we will still need to load them because it helps with debugging.

**Comment by dustine32** [comment]
@ukemi Thank you! I'll see about why those R-HSA-9708296 entities (e.g. "Pre-tRNA substrate of ELAC2") aren't recognized as more specific types. But this fix can wait until after the load.

Speaking of which, I can make a PR to the "prod" `noctua-models/master` branch with this set of models and it will be ready for merging/loading on Thursday (if that is the plan). Just to confirm, model state for these should remain "Development" in Noctua prod, correct?

**Comment by deustp01** [comment]
Checked the GO-CAMs from the new cobalamin pathways and a small arbitrary sample of other new pathways; all look plausible

> Preliminary report of just R-HSA pathway models added or removed between the release loaded into Noctua prod and the newest Reactome release 80:

Checked the three new cobalamin GO-CAMs and a small arbitrary sample of others - all look OK, as expected, so no evidence of problems with the model reload last night.

(We should probably make this morning-after check of a sample of new models a standard part of our release protocol.)

**Comment by ukemi** [comment]
Thanks @deustp01 (and @dustine32) !!! I agree a sanity check is a good idea. I will close this ticket and move it to 'done'. I will go through and make sure that I add any outstanding issues as their own tickets and to the release 82 load ticket.
