### ISSUE TITLE
Infer transport reactions as biological processes

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#17]
> For transport reactions, like “beta catenin translocates to the nucleus”, you can identify these since they have the same input and output entity, but presumably the entity is in different locations.  If there’s no controller, you should not try to infer an enabled_by, and you can label it as a GO biological process instead of a molecular function.  In this particular case, they’ve annotated it to the GO process term “regulation of canonical Wnt…”, which is a strange choice but you can still use it in the conversion.

And previous thoughts on this:
If transport reactions can be detected, convert has_location relations to either has_target_end_location or has_target_start_location and add a general class along the lines of ‘establishment of protein localization.  This will allow for the inference of biological process classes such as Establishment of protein localization to mitochondrial membrane.  For example,

The GO OWL Class: Establishment of protein localization to mitochondrial membrane is equivalent to the intersection of classes:
Establishment of protein localization
And (‘has target end location’ some ‘mitochondrial membrane’)

Consider a transport reaction from Reactome
Could make assertions according to the rule:

R instance_of ‘establishment of protein localization’
R has_target_end_location location2
R has_target_start_location location1
<=
R has output P2, 
P2 occurs_in location2, 
R has input P1
P1 occurs_in location1
P1 = P2 
location1 != location2

Then reasoner should add more specific biological process - e.g.
R instance_of ‘establishment of protein localization to mitochondrial membrane’ 
Based on its definition
'establishment of protein localization'
 	and ('has target end location' some 'mitochondrial membrane')

**Comment by goodb** [comment]
regarding 'In this particular case, they’ve annotated it to the GO process term “regulation of canonical Wnt…”, which is a strange choice but you can still use it in the conversion.'  

This actually is already used in the conversion, but not to assign a type to the reaction node.  The reaction node is made 'part of' the process that Reactome tagged it with.  You can see this happening in noctua-dev for the reaction 'Beta-catenin translocates to the nucleus' in the pathway 'Disassembly of the destruction complex and recruitment of AXIN to the membrane'

**Comment by goodb** [comment]
Should this cover the transport of complexes or just individual proteins?  Would those result in different GO classifications?

**Comment by goodb** [comment]
Looking at OWL, making call that it should only apply to proteins.  Otherwise need to find different GO classes to use.

**Comment by deustp01** [comment]
@goodb commented a long time ago, "In this particular case [“beta catenin translocates to the nucleus”, Reactome] ... annotated it to the GO process term “regulation of canonical Wnt…”, which is a strange choice but you can still use it in the conversion."
The reason for this assignment takes us off on a tangent from the central issue of this ticket. It happened because the transport reaction is part of the larger process of Wnt regulation and the Reactome curator did not associate a GO biological process term with the transport reaction. In a case like that (event instance has no BP term) the script that generates the Reactome GAF looks at its parent event and if the latter has a BP term it assigns that term to all proteins involved in  the child event. Here that has resulted in the reasoning that as catenin transport is somehow part of Wnt regulation, it can get a Wnt regulation transport term.
The durable fix for this is for Reactome curators to become better at assigning BP terms and to assign them to leaf events, not only to higher-level processes. That's an enormous clean-up process. Perhaps a pilot-scale start would be to try to generate a list of strange choices of BP terms to look for patterns and also for cases that seem especially strange hence first targets for cleanup.

**Comment by goodb** [comment]
@deustp01 I'm trying to parse the above, is there anything wrong with the logic for this conversion as it stands? e.g. see the translocation reaction in http://noctua-dev.berkeleybop.org/editor/graph/gomodel:-1280847518  
<img width="863" alt="screen shot 2018-12-09 at 3 45 39 pm" src="https://user-images.githubusercontent.com/2086122/49698841-b410f600-fb86-11e8-81e6-a7706e2ac0d6.png">

If I understand, things are working here on my end and will evolve naturally as Reactome makes changes upstream.  And I'm assuming your are talking about the BioPAX export, not the GAF generation right?  Otherwise I'm not quite understanding.
