### ISSUE TITLE
Signalling by insulin receptor (R-HSA-74752 )

### ISSUE THREAD

**Issue by ukemi** [geneontology/pathways2GO#183]
- [x] Make mouse models
- [x] Pathway boundary question- Would R-HSA-74718 fit better under R-HSA-77387? The internalization isn't really part of the signaling is it? It doesn't connect to anything downstream other than the recycling steps, so is it a signal?
- [x] Make R-HSA-74716 a receptor ligand activity (GO:0048018)? Is it possible to make insulin the enabler? For the receptor activity (R-HSA-74715), is it possible to make the INSR the enabler? Interesting discussion for the weeds.
- [x] Change mapping of (R-HSA-74715) from 'transmembrane receptor protein tyrosine kinase activity' to insulin receptor activity (GO:0005009).

Detailed comments below - conclusions are:
R-HSA-74718 / boundary issue - resolved, I think
R-HSA-74716 - current Reactome data model doesn't allow this
R-HSA-74715 - MF term changed to GO:0005009

**Comment by ukemi** [comment]
So based on what you say above, that makes sense. So in GO-CAM speak, the internalization would be embedded between the autophosphorylation and the cascade? Am I understanding that? It seems reasonable to me.

**Comment by deustp01** [comment]
> the internalization would be embedded between the autophosphorylation and the cascade?

Yes - I will re-do the event order in Reactome, and check the preceding / following annotations on the affected events. (I'm hoping that if Reactome asserts that event A precedes event B, that assertion gets into the BioPAX export and is used to drive the creation of at least a causally-upstream-of connection between the affected events.)

**Comment by deustp01** [comment]
> * Make R-HSA-74716 a receptor ligand activity (GO:0048018)? Is it possible to make insulin the enabler?

Now, neither is possible. As an editorial policy we prohibit creation of catalystActivity instances whose molecular function attribute is anything except an instance of catalyst activity or transporter activity, so we can't associate receptor ligand activity (GO:0048018).

In the future, though, nothing in the data model prohibits creating catalystActivity instances with other kinds of molecular function attributes. In fact, we have created ones with binding activity in the past and nothing broke in the data base or the web display. If we go down this road, I would want to create a new class, bindingActivity, with attributes GO molecular function (required) and enabler (optional), where the curator could use the enabler attribute to identify the gene product among all the entities participating in the binding event, that enables the binding. (N.b. I'm not sure this correctly and reliably captures the concept of enabling_of_binding, but we can work on guidelines for correct use of that slot.)

**Comment by deustp01** [comment]
> * For the receptor activity (R-HSA-74715), is it possible to make the INSR the enabler?

Now, no. In the future, we would need an "enabler" attribute, perhaps attached to the event class, to hold this information, as well as rules for how to use it in curation

> Is there any way you can add 'receptor internalization' to the black box reaction while you are at it?

Yes, I can add a biological process attribute to any event. (Remember that when we mine our data for gene product : BP mappings for our GAF, we traverse the event hierarchy bottom up, so if a reaction has its own BP term we do not look at its parent pathway to find a BP term.)

**Comment by ukemi** [comment]
> 

        For the receptor activity (R-HSA-74715), is it possible to make the INSR the enabler?

Now, not now. In the future, we would need an "enabler" attribute, perhaps attached to the event class, to hold this information, as well as rules for how to use it in curation

Sorry, not an enabler, a catalyst activity. That's what we mine to get the GO-CAM enabler.

**Comment by deustp01** [comment]
> * Change mapping of (R-HSA-74715) from 'transmembrane receptor protein tyrosine kinase activity' to insulin receptor activity (GO:0005009).

Problem: we are asserting that the input complex catalyzes its own phsophorylation so in the Reactome view tyrosine kinase activity is correct. More weeds to discuss!

**Comment by ukemi** [comment]
Sorry @deustp01. I saw all the tasks were done, so I closed this one a couple weeks ago.

**Comment by deustp01** [comment]
Re-opened to make one more fix that I overlooked earlier.
Found two candidate enzymes to catalyze the dephosphorylation of the insulin receptor in the endosome ([R-HSA-74733](https://curator.reactome.org/PathwayBrowser/#/R-HSA-74752&SEL=R-HSA-74733&PATH=R-HSA-162582,R-HSA-9006934)), so added that information. Also added 12 input H2O's to balance the 12 output phosphates, so the reaction can now "map up" to the generic Rhea reaction ([Rhea:10684](https://www.rhea-db.org/rhea/10684)) for dephosphorylation of a protein tyrosine residue.
Note the two possible long-term issues:
- the idea of "mapping up from a specific Reactome reaction to a more general Rhea one (here I expect Rhea will not want to create new reactions because the generic one already fully specifies as much of the chemistry as they want to capture)
- annotation pf proteins with weak or conflicting evidence (here, I think it is unclear how many phosphatases perform this reaction in vivo and whether different ones do it in different tissues or different physiological states). Candidate sets make this easy - do we want guidelines and limitations?
