### ISSUE TITLE
add contributed_by statements as Reactome wants them

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#38]
This is pending decisions about what Reactome curators to see here.

**Comment by goodb** [comment]
@deustp01 a gentle ping on status?  Would love to incorporate this update into the next batch conversion.

**Comment by deustp01** [comment]
Sorry! Anyone worked on an item as a curator, editor, or reviewer should be credited but these specific roles don't matter. So if you can grab the names associated with the "created", "edited", and "reviewed" attributes of the pathway that is being converted and then uniquify the list (if the same person had more than one role, only one mention is needed) that should work. Some very old pathways may lack associated person names, because we weren't using these attributes consistently at the start of the project. In those cases, the information has been lost so, if this doesnb't break anything on your end, no one gets credit.

**Comment by goodb** [comment]
Right now we are using http://purl.org/dc/elements/1.1/contributor to link models to contributors.  It doesn't officially require a URL, but our software generally expects one.  e.g. orcid ids like http://orcid.org/0000-0003-3641-7548  .   As it stands, I can mine comments for strings like: "Edited: Shamovsky, V, 2010-02-27" but it would be much better in the long term if your team could replace those with orcids.  Let me know if there are any plans to make a change like that.  If not, I will go ahead and add the names as Strings and see what happens.

**Comment by goodb** [comment]
In fact, at the pathway level, these comments are already there in the models, you just can't see them in Noctua.  (You can see them in Protege if you look at the model that way).  e.g. 
![screen shot 2019-01-17 at 3 57 18 pm](https://user-images.githubusercontent.com/2086122/51356754-ad707b00-1a70-11e9-8aa8-69cffcca9b4b.png)

**Comment by ukemi** [comment]
@goodb 
Are you going to recalculate the models. I have been working on the one that is linked from the document.

**Comment by goodb** [comment]
Yes, there are a lot of improvements I want to push.  If you want to preserve any of your changes you will want to save them somewhere else either as a model with a different name or as a new model in main noctua.  noctua-dev is not a stable collection.

**Comment by ukemi** [comment]
I can't seem to save the current model under a different name.

**Comment by ukemi** [comment]
Thanks @goodb. I'm seeing some pretty consistent things that I think can be codified wrt limiting models.

**Comment by goodb** [comment]
@deustp01 I believe we are okay to close this, yes?

  Each model refers to the original source in Reactome which carries the complete attribution data.  In addition, the root pathway node for each model brings over the text for the pathway editor, reviewers, etc.  

When reactome updates its own internal attribution model and this is made available in the BioPAX lets open a new ticket to enhance the models as appropriate.

**Comment by deustp01** [comment]
OK to close.
