### ISSUE TITLE
Systematic Review of Pathway Conversion

### ISSUE THREAD

**Issue by ukemi** [geneontology/pathways2GO#40]
@vanaukenk, @huaiyumi, and I will work with @deustp01 on a curatorial review of the conversion of specific pathways to see if we can identify systematic issues.
The goal will be to compare the Reactome representation, the Reactome-based GO-CAM and potentially a curator generated GO-CAM to see if the models are faithfully represented. We will have virtual meetings to discuss the models each week. For each meeting one person will report their findings and then we can discuss any issues. I will start with glycolysis.

There is a [folder in the GO-CAM and Noctua folder](https://drive.google.com/drive/u/0/folders/1nOLeeA9OtkI37_xIcg5vvMaoq6ucVHJ-) for the reactome project. I suggest we put notes and presentations there.

Pathways claimed:

- [x] @huaiyumi - Signaling by BMP (R-HSA-201451.4); BMP signaling pathway (GO:0030509)
- [x] @huaiyumi - MAPK1/MAPK3 signaling (R-HSA-5684996.4)
- [x] @ukemi and @deustp01 - Glycolysis (R-HSA-70171); canonical glycolysis (GO:0061621)
- [x] @ukemi and @deustp01  - Gluconeogenesis (R-HSA-70263); gluconeogenesis (GO:0006094)
- [ ] @vanaukenk - TCF dependent signaling in response to WNT (R-HSA-201681); canonical Wnt signaling pathway (GO:0060070) Not xref'd but generic pathway is.
- [x] @vanaukenk - Unfolded Protein Response (UPR) (R-HSA-381119); endoplasmic reticulum unfolded protein response (GO:0030968)
- [x] @ukemi and @deustp01 - GABA degradation (R-HSA-916853); gamma-aminobutyric acid catabolic process (GO:0009450)
- [x] @ukemi and @deustp01  - PINK/PARKIN Mediated Autophagy (R-HSA-5205685); mitophagy (GO:0000423) or macroautophagy (GO:0016236).

**Comment by huaiyumi** [comment]
There is a Reactome_and_Pathway_Mapping folder already. I created a Systematic_Review_Reactome_Conversion subfolder. Let's put our notes in that folder.

**Comment by goodb** [comment]
It would be useful to go ahead and make an example of the pathway or at least the pathway components of interest alongside google docs [like Huaiyu has started](https://docs.google.com/document/d/1H0vcz6QNjSCxHd3tAENiTJoXY7XZnaTHrIwKCXwkHRw/edit).  I suggest doing this in real noctua (not noctua-dev) so that the results are stable.

**Comment by huaiyumi** [comment]
I just finished the BMP pathway except for the evidences/references. I generated 2 GO-CAM models. One is a more direct conversion of the Reactome pathway based on the information provided by it. I think a computer program can convert most of the reactions like this. The other uses the existing GO annotations to minimize the protein binding nodes. It will be difficult for a computer program to do it, because a lot of information is stored elsewhere. I have detailed notes in the google drive. Happy to discuss.

**Comment by ukemi** [comment]
Fantastic! I have created a template for glycolysis with no genes annotated to it. I am in the process of comparing the curated one, the one generated from the Reactome import and the Reactome view of the pathway on the Reactome pathway viewer. I am noting the differences in the representation in a spreadsheet. I thought we would look a this next Wednesday and then do BMP after that, probably in two weeks because of the hackathon. But if you want to do BMP next Wednesday that would work too. I think we should focus on one pathway per meeting. All of my stuff is in the shared drive. I am still working on the spreadsheet. I hope to get it finished tomorrow.

Tagging @balhoff because I left him off of the first invitation set.

**Comment by goodb** [comment]
@ukemi I think its important that we attempt to capture any additions or changes to the mapping rules at the end of each of these meetings.  If such conclusions can be figured out in advance by the presenter, all the better.  

I don't think we had any specific suggestions for changes to the import logic this time.  

The conclusions I remember from the meeting:
1. GO is very inconsistent with how it decides whether to create a Complex in the CC ontology or not.  This is an issue that percolates across the GO and is not unique to the Reactome problem.  
 (BG: M take on the relation to Reactome is to insure that the protein products that compose the complexes make it into the GO-CAM models in a way that, should logical definitions of complexes exist or be created - either based on their parts or their activities - the complexes can be classified automatically.)

2. The connections linking nodes in the pathway off to nodes in other pathways tend to obscure the model.  Potential resolutions: a) eliminate cross-pathway connections or b) implement changes in Minerva/Noctua to allow them - including UI code which would allow the user to choose whether to display them or not.  Note that this particularly influences regulatory relations.

**Comment by deustp01** [comment]
1. Let me look at the GO complex hierarchy to see if there are terms there that could be used as Ben suggests to organize complexes we're importing from Reactome to GO-CAM so that future logic could be applied. If I get anywhere, a topic to discuss next time.
2. I'm thinking of GO-CAM models as visual representations of processes (which may be completely wrong now, maybe always). On the visual model, then visual cues to show a viewer where it's possible to walk off the edge of the process diagrammed in the GO-CAM and get to someplace else that's interesting adds value. It's now a usability / design issue (which my colleagues tell me I have all the wrong instincts for) to figure out how to show those off-the-map destinations and what kind each one is. Iconographies, color schemes, graying-out, and toggles all come into play here.

**Comment by ukemi** [comment]
There are suggestions at the bottom of the document in the drive.

**Comment by goodb** [comment]
Just summarizing state of affairs here.  We have implemented most of the changes that have emerged from the three specific pathways that have been reviewed in these meetings (as indicated by the checkboxes in the original issue description).  Today there are three open issues we could try to resolve: 

The main unresolved issue is whether or not to keep/modify the sequestration rule:
https://github.com/geneontology/pathways2GO/issues/62

Some additional input on whether or not the biocuration team here is happy with the resolution to the representation of reactome sets embedded in complexes would be useful to close.  
https://github.com/geneontology/pathways2GO/issues/61

And finally, we need a decision on whether we are happy with or need changes to how the go-cam functions are represented when their components occur in multiple locations:
https://github.com/geneontology/pathways2GO/issues/59 

Next steps involve either the review of the GPAD outputs for these pathways or the continued review of the other pathways mentioned when the issue was generated - e.g. TCF signaling.

**Comment by ukemi** [comment]
The annotation comparison for 'glycolytic process' is shown in this spreadsheet:
https://docs.google.com/spreadsheets/d/1jgXRmjC6w2yghs_wldYrM3rSZbDbCZYF-_VD66-Uwkc/edit#gid=0
Green annotations are from GO-CAM and Blue are from an AMIGO2 query of Annotations derived from Reactome. I have also added orange annotations which represent MF annotations for the gene products associated with glycolysis in the current AMIGO2 load. I think this sheds a lot of light on the plan to somehow categorize 'emergent' functions and where we stand with respect to that and current annotation state. These are interesting observations to note and discuss, most of which I think stem from teasing out functions from complexes.

**Comment by ukemi** [comment]
Gluconeogenesis is here:
https://docs.google.com/spreadsheets/d/1FB2ps8x_G6ZLOTmMBIQXNZ4Dam2CaOkyovZusdlQCp8/edit#gid=0

**Comment by deustp01** [comment]
Comments on the glycolysis and gluconeogenesis annotation comparisons are here (new document added to the 2019-Pathways2GO-NYC > Annotation Analysis folder): https://docs.google.com/document/d/1u3bwQ334eypPvGZ9GzVrB-oK9x7u2NfSWVQ4cwag62c/edit.

**Comment by ukemi** [comment]
Thanks @deustp01. I'm going to try to do the unfolded protein response today, then I will be invisible until Monday.

**Comment by ukemi** [comment]
I think we can close this ticket and roll it into the manuscript.

**Comment by deustp01** [comment]
Nothing here to get in the way of closing.
