### ISSUE TITLE
validate consistency of reactome location curation

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#48]
One of the rules applied during import to go-cam infers. reaction location from entity locations

Possible QA bonus: Reactome is supposed to do this manually and record the result as an attribute of the reaction, so the inference should match the annotation and discrepancies are likely curation mistakes.

The work in progress at Reactome to sort out "encloses" relationships among GO cell_component terms used to annotate locations of entities and reactions should be usable also to check plausibility of reactions with multiple locations.

**Comment by goodb** [comment]
Processes in GO now use the 'has primary input' relation in their definitions.  Reactome doesn't distinguish something as primary, hence we will not be matching the GO logical definitions very often any more.  We can still use this as a curation check on Reactome. e.g. glycolysis should have glucose as an input.

**Comment by ukemi** [comment]
Note that the the 'primary' relations are only used for GO metabolic processes at this time.

**Comment by deustp01** [comment]
Later thought after the discussion yesterday: Perhaps Reactome could annotate primary inputs and outputs, by creating primary input and output attributes for its pathway class, that would take one or more physical entities as values. And perhaps a GO QA script could retrieve the GO biological process term, if any, associated with a Reactome pathway, retrieve the primary inputs and outputs named in the logical definition of that term, if any, check the Reactome pathway for the presence of the inputs in its first reaction and outputs in its last one, and complain if they are missing. Note the substantial maintenance overhead caused because both Reactome pathway makeup and GO biological process definitions can change substantially over time, so continued checking and patching will be needed.

**Comment by deustp01** [comment]
> Note that the the 'primary' relations are only used for GO metabolic processes at this time.

But it looks like a really good way of formalizing pathway boundaries and should be easy to extend to signaling cascades, and to localization processes involving individual proteins and complexes.

**Comment by ukemi** [comment]
Thus the 'at this time qualifier'. We think alike.

**Comment by ukemi** [comment]
Closing this one. QC will be done on the Reactome side where they will be able to highlight inconsistencies to their curators.
