### ISSUE TITLE
Implement rules for assigning occurs_in relations to molecular function nodes 

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#51]
Right now, the converter adds all of the locations of all of the entities involved in a reaction as values on function occurs_in location statements.  

This is a change from the initial rule that occurs_in would only be asserted if all entity locations were equals.  The reason for the change is that, without it, the location information for cross-location reactions is completely lost in the conversion.  (It could be kept by adding entity located_in location statements into the models but that totally obscures the view in Noctua because of multi-level folding issues and is apparently not desirable from the standpoint of the GO-CAM domain model.)  

So, what should be do in the conversion for situations like this ?

![screen shot 2019-02-14 at 11 02 49 am](https://user-images.githubusercontent.com/2086122/52810740-18997700-3048-11e9-9a0a-5e84ea6af5f7.png)

**Comment by ukemi** [comment]
Although it is possible in cases where the actual location represents a compound term such as endosome membrane being represented as endosome and membrane if the former were not instantiated. In this case this case this is incorrect because these CCs are spatially disjoint. I found some of these that negated some of the original rules for annotation extensions. @cmungall this seems like a good argument for adding spatial disjointedness axioms to CC (and UBERON?). We will have to look at the Reactome model closely to figure out where the binding event actually takes place.

**Comment by cmungall** [comment]
I would have thought PM + cytosol would have violated our existing axioms

ticket to add more: https://github.com/geneontology/go-ontology/issues/16785

**Comment by goodb** [comment]
Perhaps what we are looking at here is a process and not a specific function from the perspective of the GO.  What about breaking the reaction into a process with three different MF nodes, each with the appropriate localization?  

I guess a challenge there is getting the ordering right.

**Comment by ukemi** [comment]
And determining if the functions actually occurs there. But as an aside, I think we should talk about the idea of checking all these models with current GO representation/axioms. We poked at it a little, but I think it would really help improve the resources.

**Comment by ukemi** [comment]
So the philosophical question that would support Ben's idea is that does the binding function occur ass long as the participants are bound, or do we only consider binding to be the initial convergence of the participants. If the former, then the binding can occur in spatially disjoint CCs if the complex moves.

**Comment by ukemi** [comment]
Sorry, but continuing to think about this. I like @goodb 's idea more and more if the goal of this project is to get precise and faithful representation of the Reactome pathway in GO-CAM. Breaking up the binding into three MFs that each occur in a different location would allow us to get precise spatial resolution of the events. Another approach would be to invoke a transport process that moves the complex from place to place, but if that isn't a separate process enabled by GPs, then I think that is not in line with our views.

**Comment by deustp01** [comment]
This is hard because some key bits of biology are unknown. The annotation asserts that a BMP complex initially in the plasma membrane, a SMAD protein initially in the cytosol, and a ZVYFE protein initially in the membrane surrounding an endosome vesicle in the cytosol all coordinately interact and bind one another, resulting in a BMP - SMAD - ZVYFE complex located in that membrane. In reality, it's probably not a concerted reaction, but sequential steps in which components are recruited to a complex forming around the BMP part as it moves from the plasma membrane to the endosome membrane, but we only know enough to annotate the beginning and end states.
<img width="558" alt="screen shot 2019-02-27 at 1 37 17 pm" src="https://user-images.githubusercontent.com/12737623/53514131-fd415980-3a94-11e9-8f17-512e982eb485.png">

Biologically,the locations of entities and the changes in their locations as this reaction proceeds are important but if we can't have both accurate parts lists for the complexes and accurate diverse locations for the parts, the parts lists are probably more important.

There may be a variant of question 4 (Can a reaction both 'directly provide input for' and 'positively regulate' another reaction?  See [#49 ](https://github.com/geneontology/pathways2GO/issues/49#issuecomment-463730529)) buried in here, in that as the complex assembles each intermediate is both input for and enabler of the next step of assembly.

**Comment by goodb** [comment]
Notable that the first step of the conversion process is a more direct translation of the Reactome content, using the located_in relationship.  At one point we had it set up such that reaction/function nodes only received the occurs_in statement when all of the locations on all relevant entities were the same.  

This is what it would look like without the occurs_in translation.  
![screen shot 2019-02-28 at 8 15 54 am](https://user-images.githubusercontent.com/2086122/53581352-3f6ca880-3b32-11e9-8ce4-d0b1283802c8.png)

**Comment by vanaukenk** [comment]
@goodb 
From 2019-03-01 discussion at NYU:
In cases where a reaction occurs in more than one place, Reactome curators will look to see if there is  a single GO CC term that can be used to describe where that reaction occurs, e.g. cytoplasmic side of  endoplasmic reticulum membrane.
GO will need to see if there are any locations that are not represented in GO CC and should be added.

**Comment by goodb** [comment]
@vanaukenk see question 1 in https://github.com/geneontology/pathways2GO/issues/55 
If Reactome starts attaching location information directly to reactions rather than to physical entities, we need to be sure that information is coming out in the BioPAX export.

**Comment by ukemi** [comment]
https://github.com/geneontology/molecular_function_refactoring/issues/45

**Comment by goodb** [comment]
Resolving that the answer, for now, is yes.  Reactome does not want to annotate location at the level of the reaction and, in any case, this can't be expressed using the current BioPAX model which only allows locations on physical entities.  The consequence is that reactions from Reactome that are turned into function nodes will often end up with multiple occurs_in statements attached.  This is now curation issue for Reactome to consider.  (The alternative is to move location information to entities in GO-CAM, but no one wants to do that right now.)

**Comment by deustp01** [comment]
> The alternative is to move location information to entities in GO-CAM, but no one wants to do that right now.
Ben, could you explain that a bit more during the teleconference tomorrow? My biologist instinct is that entities are tangible physical objects therefore have locations, while reactions are arguably abstract relationships that don't necessarily. Unless the reason for no one wanting to do it is simply that it is hard and other hard problems are more urgent.

**Comment by goodb** [comment]
@deustp01 I will need @ukemi or @thomaspd to explain this as I don't really understand why they are so opposed to it.  This is related to the opposition to letting entities be linked to functions via e.g. involved_in_regulating relations.  I think the main theme here is the desire to move information off of entities and onto activities - following the 'activity flow' paradigm.  

This is a modeling question only.  The code in fact starts out by adding all of the location information to the entities, uses that information to infer function and process location, and then discards the entity locations.

**Comment by deustp01** [comment]
@goodb @ukemi @thomaspd that last activity flow explanation from Ben in fact resolves the issue*. When the entities involved in a reaction are all in a single place, that place is the location for the reaction so it can be captured from Reactome into the GO-CAM model.

When the reaction involves transporting entities from here to there through an intervening barrier, I guess that GO has an opinion about where that reaction / activity is located and again in most cases (the one that started this thread is a rare exception and probably a curation mistake) that location can be chosen or computed from the ones annotated by Reactome for the participating entities and attached to the GO-CAM activity model.

When a reaction is catalyzed or something is regulated, the location of the catalyst or the regulator is the activity location that GO wants for the GO-CAM model.

In other situations where a Reactome annotation provides multiple entity locations, that information is out of scope for GO so the GO-CAM model actually should not capture it.

Does this work? (*The proper scope of GO is a useful continuing discussion, but not here.)

**Comment by ukemi** [comment]
My initial discomfort with just having the location of the entities lies more in the general GO paradigm, of which the 'ultimate' representation is to use cellular components to describe where the molecular function of a gene product is enabled. From a GO curation standpoint, that's my goal.

**Comment by ukemi** [comment]
I'm warming up to @deustp01 's proposed solution above. If all of the participants are located in the same structure, then the function/process occurs in that structure. If they don't then just skip the location information. We need to look at this in the context of a couple of the examples, because I think it also impinges on our 'transport' rules.

**Comment by cmungall** [comment]
It's never wrong to use the MRCA of all participants (on the isa/part-of graph). Of course, this will often end up with cell or "cellular_component", so precision will be lost. If all participants are in the same location then of course the MRCA is that location.

If we have an enabler, can we use the location of the enabler?

**Comment by ukemi** [comment]
We could just assert the location of the participants, but that is still a bit unsatisfying wearing my GO hat. Ideally we would be able to do something like say if the enabler is in the plasma membrane and the inputs and outputs are in the cytosol, then the activity takes place on the cytosolic side of the membrane. We have these kinds of terms.

**Comment by deustp01** [comment]
> If we have an enabler, can we use the location of the enabler? (cmungall, above)
Yes, exactly - that's what I was suggesting for catalysis and regulation, and it works as well for transport whenever we have identified the entity that is mediating the transport.

**Comment by ukemi** [comment]
I think this is a good idea. It may not be as precise as we could possibly get, but I don't think it will ever be wrong.

**Comment by ukemi** [comment]
@cmungall brings up an excellent point though. We could use the MRCA to group process locations. These would correspond to the boxes that Reactome curators draw by hand in the pathway diagrams.

**Comment by goodb** [comment]
So something like this?
**the objective is one cellular location per molecular function node** because.. thats how we do things I guess.   

1. Transport reactions are turned into 'transport' or 'protein transport' biological processes.  No occurs_in statements are added to these.  Location information is added using the 'has start location' and 'has end location' relations.

2. For reactions where all entities are in one location, the reaction occurs_in that location

3. For reactions with multiple entity locations, that are enabled by something, the reaction occurs_in the location of the enabler.  Other location information is dropped.  

4. For reactions with multiple entity locations and no enabler, find the MRCA of all the locations and assert that as where the reaction occurs.  (What happens if there is more than one common ancestor at the same distance up the ontology?  Guessing that can happen.)  

?

**Comment by cmungall** [comment]
Actually I am not sure MRCA is guaranteed safe. The following
counter-example may be fake but it illustrates.

If one participant is in organelle X, and another is in (a distinct
instance) organelle Y, and no other participants are explicitly stated,
it's not necessarily correct to say the activity happens in an organelle.

Maybe this never happens with organelles, but substitute this for any class
for which there may be two separate instances in the model.

>

**Comment by ukemi** [comment]
I think you are correct.

**Comment by deustp01** [comment]
A possible test would be to ask if all the named locations can be linked by surrounded_by relationships. If not, there's a problem that requires human intervention. This test would allow combinations like organelle membrane and cytosol, or organelle lumen and organelle membrane, but not organelle X (or any part_of organelle X) and organelle Y (or part).

**Comment by ukemi** [comment]
Do you guys ever have cases where reactions could span gross anatomical structures, like cholesterol transport for example? I think that would create the kinds of problems that @cmungall came up with.

**Comment by deustp01** [comment]
We evade those long-distance transport issues by having a universe that consists of one cell surrounded_by extracellular space, so for that cholesterol transport case, we'd annotate the events that mobilize it and get it out of a peripheral cell, then annotate the events that get it taken up from extracellular space into a liver cell for further metabolism. The Reactome data model is unaware of that  "peripheral" - "liver" distinction so strictly the annotation says that intracellular cholesterol is mobilized and exported from the cell, then taken up by the cell and metabolized further. But if you look at a pathway where this is actually happening like [bile acid synthesis](https://reactome.org/PathwayBrowser/#/R-HSA-194068&SEL=R-HSA-192105&PATH=R-HSA-1430728,R-HSA-556833,R-HSA-8957322) you'll see that each reaction either occurs at a single location or moves stuff between two adjacent ones (though that depends on curator alertness; there's no rule to force that behavior). When you look at the pathway diagram on the Reactome website, you'll see that several separate cells have been laid out and cholesterol is mobilized in the one on the left, made extracellular, and taken up by the middle one that fills most of the diagram for conversion to bile acid. Those cells, however, are hand-drawn by the curator - the data model is unaware of them.

**Comment by ukemi** [comment]
So if you look way over at the right where the ALB is, there is no way to distinguish between the two plasma membranes.

**Comment by deustp01** [comment]
Exactly. A human who knows the biology may conclude that the leftward one belongs to a hepatocyte and the rightward one belongs to an intestinal epithelial cell, but the data model has no way to reach that conclusion. But at the same time note that the transport reactions in that part of the diagram involve transport events that move molecules between two aqueous compartments separated by a lipid bilayer membrane. The craziness becomes apparent when you string multiple reactions together to depict the events that take a bile acid all the way from liver cytosol to intestinal cell cytosol.

**Comment by goodb** [comment]
inconsistency problem occurs when complexes enable functions that occur in both extracellular and intracellular space
![screen shot 2019-03-06 at 2 21 45 pm](https://user-images.githubusercontent.com/2086122/53919620-71dd4080-401f-11e9-88ef-c0b857a4ceb0.png)

**Comment by ukemi** [comment]
The more I think about this with respect to the discussions above, the more I am inclined to conclude that for the time being if the reactants are in more than one place and the enabler's location is not specified, we can't safely conclude where the enabler functions. I was also concerned with the reasoner results that inferred a transport as a cytosolic transport when the model showed it occurred in the cytosol and somewhere else. The reality is that part of the transport process occurs in the cytosol and part of the transport process occurs in the other cellular component. I think (hope) the new rules with start and end location will solve this issue for transport, but there are other rare cases where we have differentiated functions or processes by where they occur. In those cases if there is a corresponding reaction in the model that corresponds to one of those locations, we might make an incorrect inference. The MCRA solutions seems like it would be elegant, but as discussed above it also introduces caveats. 

I can't help but wonder that the way to solve these issues properly is to continue to add and refine spatial information in the ontology. Since @deustp01 's has already requested this for their work, I would propose that this becomes a high-priority ontology development project once @vanaukenk and I have completed the legacy annotation load project. I suspect that if @balhoff, @cmungall , @vanaukenk , @deustp01 , @goodb and I put our heads together with respect to spatial relations and how to use them in the ontology, we might be able to come up with some valuable inferences. I have started a project in the ontology tracker for this.

**Comment by deustp01** [comment]
Adding and refining spatial information will certainly help.

Meanwhile, for the specific case of building GO-CAM models from Reactome annotations, we can treat reactions where participants have more than one location and no location is specified for the reaction's enabler as a QA issue. (Note that this situation will almost always arise because no enabler is specified: Reactome already has a rigid rule, enforced by good QA, that physical entities must have locations.) Provisionally don't localize the reaction, but compute its MRCA location and refer the reaction and its MRCA prediction back to Reactome for human inspection, possible approval of the MRCA prediction, and possible re-annotation.

I expect that only a small fraction of reactions will be flagged this way, and that they will mostly fall into a small number of patterns for which we will have standard responses either on the GO-CAM computational side or the Reactome annotation side. These in turn should yield better curation QA on the Reactome side and tests for situations when computational inference in reliable on the GO-CAM side.

**Comment by ukemi** [comment]
Since we can't safely use a MRCA, if there is no enabler, then we can't capture location information.

**Comment by goodb** [comment]
Restating complete rules with not MRCA for confirmation:

1. Transport reactions are turned into 'transport' or 'protein transport' biological processes. No occurs_in statements are added to these. Location information is only added using the 'has start location' and 'has end location' relations.
2. For reactions where all entities are in one location, the reaction occurs_in that location
3. For reactions with multiple entity locations, that are enabled by something, the reaction occurs_in the location of the enabler. Other location information is dropped.
4. For reactions with multiple entity locations and no enabler, do not assign any occurs_in relation.  

yes ?

**Comment by goodb** [comment]
@ukemi what would happen if a reaction was enabled by more than one thing and those things were in different locations ?

**Comment by ukemi** [comment]
Hmm. I'd like to see some examples. It may be in those cases we could use the MCRA. @deustp01 can you shed any light on when this would happen?

**Comment by goodb** [comment]
@ukemi I don't know if that will happen or not, just looking for edge cases to complete the conversion logic.  

More concerning is the loss of any location information at all for things happening at receptor interfaces, e.g. https://reactome.org/PathwayBrowser/#/R-HSA-201451&SEL=R-HSA-201457 

And also not happy with transport as it stands.  Consider e.g. [The phospho-R-Smad1/5/8:Co-Smad transfers to the nucleus](https://reactome.org/PathwayBrowser/#/R-HSA-201451&SEL=R-HSA-201472&PATH=R-HSA-162582,R-HSA-9006936) .  For these, we get:
![Screen Shot 2019-03-20 at 8 58 43 AM](https://user-images.githubusercontent.com/2086122/54701105-8a565c00-4af1-11e9-90ac-6109e3b72201.png)
which does not result in any further inferences based on logical definitions.  

I'd like to see this inferred to be e.g. 'import into nucleus' but the definition doesn't quite line up.
transport
 and ('has target start location' some cytosol)
 and ('has target end location' some 'nuclear lumen')
 and ('results in transport across' some 'nuclear envelope')

Questions:
- Should annotations to 'nucleus' in Reactome perhaps be to the more specific 'nuclear lumen' in many cases like this one?
- Doesn't start location cytoplasm and end location nuclear lumen imply transport across nuclear envelope?  Could that definition be amended to leave the transport-across part out? Alternately, is that a property chain that should be added?  Alternately, should the import code make that conclusion when it sees the cytosol / nucleus combination for inputs and outputs ?

**Comment by goodb** [comment]
Actually https://reactome.org/PathwayBrowser/#/R-HSA-201451&SEL=R-HSA-201457 is a bad example for the receptor problem.  That one ought to at least be annotated with occurs_in extracellular as that is where the catalyst is located.

**Comment by ukemi** [comment]
> Doesn't start location cytoplasm and end location nuclear lumen imply transport across nuclear envelope? Could that definition be amended to leave the transport-across part out? Alternately, is that a property chain that should be added? Alternately, should the import code make that conclusion when it sees the cytosol / nucleus combination for inputs and outputs ?

Yes. I saw this a few weeks ago when I was looking at this. I think without the nuclear envelope differentia, the definition would still be necessary and sufficient. But without the spatial information to know that is had to go across the envelope, we can't conclude that it crosses the nuclear envelope. Before we go down that route, we need to examine how the transport part of the ontology has been rearranged.

**Comment by goodb** [comment]
Updating rules based on call today:

1. When a reaction has the same input and output entity but in 2 different locations:
 - Create a node for the reaction and add has_start_location and has_end_location attributes
  - If there is something that enables the reaction, then add either 'transport' or 'protein transport' as the rdf:type of the node.  Else, leave the node with no type assignment (not an mf, bp etc. no type). 
2. For reactions where all entities are in one location, the reaction occurs_in that location
3. For reactions with multiple entity locations, that are enabled by something, the reaction occurs_in the location of the enabler. Other location information is dropped.
4. For reactions with multiple entity locations and no enabler, do not assign any occurs_in relation.

**Comment by cmungall** [comment]
I recall this discussion from a while ago, don't have ticket, but it was
felt that there were other mechanisms, e.g. traveling through a gap..

>

**Comment by ukemi** [comment]
@cmungall wouldn't this fit into 1 and 4? The node would be created, but there will be no GO process assigned to it. It allows for continuity expressed in the reactome model as things moving by mechanisms such as simple diffusion.
Once the rules are implementd, we will have to look at some cases. I think the SMAD/Co-SMAD moving into the nucleus is a good one. IIRC there is no mediator.
