### ISSUE TITLE
The converter is using a synonym rather than a primary label

### ISSUE THREAD

**Issue by ukemi** [geneontology/pathways2GO#65]
In the PARKIN-mediated mitophagy pathway(R-HSA-5205685 ) the entity catalyzing the 'Pink1 is recruited from the cytoplasm to the mitochondria' reaction has a label of 'TOMM40 complex' in Reactome, but the GO-CAM model seems to be using a synonym 'TOMM70:TOMM40'

**Comment by goodb** [comment]
The conversion uses the "displayName" property provided in the BioPax export.  This doesn't always seem to align with the names used in the Reactome display.

**Comment by goodb** [comment]
Action: Remove the content in the square brackets in the names from the displayName field.

**Comment by goodb** [comment]
@deustp01 Unfortunately things weren't quite as they seemed.  The displayName field in the BioPAX export does not match main name shown in Reactome and also does not contain the location information in the square brackets.  To confuse things, my code was adding the location information in, distinguished with (), as this was often the only difference between two otherwise identical entities.  

Bottom line, I would like to continue using the displayName field as delivered in the BioPAX because it is predictable while sampling from the synonym set is not.  I will take the '(location)' strings that my code was adding out of these names.  The result will be that we still will not have names aligning directly between the Reactome view and the Noctua view.  

The entity mentioned here is going to look like 'TOMM70:TOMM40' in Noctua while it looks like 'TOMM40 Complex [mitochondrial outer membrane]' in the Reactome viewer.  

I believe the solution to this problem is to change Reactome's BioPAX generator code to use the preferred label as the displayName.

**Comment by goodb** [comment]
FYI.  This is what the relevant part of the biopax here looks like.
![Screen Shot 2019-08-09 at 1 27 52 PM](https://user-images.githubusercontent.com/2086122/62813160-22170f80-babe-11e9-9d10-6b79fbded59f.png)

**Comment by ukemi** [comment]
OK. We can live with this.
