### ISSUE TITLE
remove contributes_to

### ISSUE THREAD

**Issue by goodb** [geneontology/pathways2GO#72]
After looking at the gpad outputs, the team decided to take the contributes_to assertion out of the converted models because it was generating far too many weakly supported annotations linking complex members to functions that they have an unknown role in enacting.

**Comment by ukemi** [comment]
Weakly supported or just plain incorrect. Because Reactome complexes often represent accessory molecules and substrates, using a contributes_to qualifier for all members is incorrect. An example of this is R-HSA-201477. This complex has an active subunit of the BMPR1A, but it also contains the SMAD protein substrates and a molecule that helps anchor it in its location. These molecules do not contribute to an emergent function of the 'transmembrane receptor protein serine/threonine kinase activity', they have separate individual functions.
